<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>SlimeLogo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="SlimeLogo.ico" />
    <None Remove="SlimeLogo.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SlimeLogo.ico">
      <LogicalName>SlimeLogo.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="SlimeLogo.bmp">
      <LogicalName>SlimeLogo.bmp</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Gum.MonoGame" Version="2026.5.8.1" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
    <ProjectReference Include="..\MonogameLibrary\MonogameLibrary.csproj" />
  </ItemGroup>
</Project>
